[tool.commitizen]
version = "0.24.0"
version_scheme = "semver2"
version_files = ["client/package.json:version", "api/composer.json:version"]

tag_format = "$version"

update_changelog_on_bump = true
major_version_zero = true
